#!/bin/sh
VERSION=6.1.0
ARCH=$(uname -m)
if [ "$ARCH" == "arm64" ]; then
	docker buildx build --build-arg VERSION=$VERSION --platform linux/amd64 --load -t omnetpp-gui:u24.04-$VERSION .
elif [ "$ARCH" == "x86_64" ]; then
	docker build --build-arg VERSION=$VERSION --load -t omnetpp-gui:u24.04-$VERSION .
else
	echo "Unsupported architecture: $ARCH"
	exit 1
fi

